package io.github.grishaninvyacheslav.geekbrains_professional_android_application_development.presenters.main

import io.github.grishaninvyacheslav.geekbrains_professional_android_application_development.presenters.View

interface MainView : View